# Based on https://github.com/pywinauto/pywinauto
#
# Hint: before committing any changes in the yaml file verify it in 
# the yaml online parser: http://yaml-online-parser.appspot.com/
#

# fetch repository as a zip archive
shallow_clone: true                 # default is "false"

environment:

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

#os:
#  - unstable # Unstable worker image with logged in user, desktop and interactive build agent

install:
  # Some listings for debug only
  #- ECHO "Filesystem root:"
  #- ps: "ls \"C:/\""
  #- ECHO "Notepad location "
  #- ps: "ls C:\\Windows\\System32\\notepad.exe"

  # install wxPython
   - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
   - "%CMD_IN_ENV% powershell ./ci/install.ps1"

  # Install the build dependencies of the project.
   - "%CMD_IN_ENV% pip install -r dev-requirements.txt"

   # Install pywinauto from the trunk
   - "%CMD_IN_ENV% pip install -e git+https://github.com/pywinauto/pywinauto.git@master#egg=pywinauto-trunk"

build: off  # disable automatic builds

build_script:
  - "%CMD_IN_ENV% pip freeze"
  - "%CMD_IN_ENV% powershell ./ci/build.ps1"

#test_script:
#  # Build the compiled extension and run the project tests
#  - "%CMD_IN_ENV% powershell ./build.ps1"

artifacts:
  # Archive the generated coverage report in the ci.appveyor.com build report.
  - path: swapy*.exe
